name: mantra_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  uuid: ^4.4.0
  audioplayers: ^6.6.0
  vibration: ^3.1.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/sounds/

  uses-material-design: true

