// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8qC5of-IwX0-AUBkN2sd5PdRsBa8ElnE',
    appId: '1:232614530250:web:479ebae4200f74898c7833',
    messagingSenderId: '232614530250',
    projectId: 'mantra-flow',
    authDomain: 'mantra-flow.firebaseapp.com',
    storageBucket: 'mantra-flow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3u4BJnxlGiPvwA2v8rd8dtLk82Kwm454',
    appId: '1:232614530250:android:31023ecc52c2a91d8c7833',
    messagingSenderId: '232614530250',
    projectId: 'mantra-flow',
    storageBucket: 'mantra-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGhG1YPBaTbSnnnIyNw-EkDbtEXs5mE8',
    appId: '1:232614530250:ios:8ad819388b9e8d2f8c7833',
    messagingSenderId: '232614530250',
    projectId: 'mantra-flow',
    storageBucket: 'mantra-flow.firebasestorage.app',
    iosBundleId: 'com.example.mantraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALGhG1YPBaTbSnnnIyNw-EkDbtEXs5mE8',
    appId: '1:232614530250:ios:8ad819388b9e8d2f8c7833',
    messagingSenderId: '232614530250',
    projectId: 'mantra-flow',
    storageBucket: 'mantra-flow.firebasestorage.app',
    iosBundleId: 'com.example.mantraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8qC5of-IwX0-AUBkN2sd5PdRsBa8ElnE',
    appId: '1:232614530250:web:9ed1781783af0acc8c7833',
    messagingSenderId: '232614530250',
    projectId: 'mantra-flow',
    authDomain: 'mantra-flow.firebaseapp.com',
    storageBucket: 'mantra-flow.firebasestorage.app',
  );
}
